### ISSUE TITLE
2 manages

### ISSUE THREAD

**Issue by afwn90cj93201nixr2e1re** [mavajee/guide__vue-cli-3-multiple-entry-points#1]
Is this a bug?
https://github.com/mavajee/guide__vue-cli-3-multiple-entry-points/blob/master/vue.config.js#L18
https://github.com/mavajee/guide__vue-cli-3-multiple-entry-points/blob/master/vue.config.js#L49

**Comment by mavajee** [comment]
Oh yeach, remove one exports
